### ISSUE TITLE
Timeout / ReferenceError: fetch is not defined error occurring when running default sample

### ISSUE THREAD

**Issue by gomezo76** [teslahunt/inventory#24]
Hum, still have an issue to run the default sample, did i miss another thing?  Context: script running on Mac M1  Ventura OS, thanks

Here the error (occurred after some minutes).
```
% node fetchTeslaInventory.js 
(node:48334) UnhandledPromiseRejectionWarning: ReferenceError: fetch is not defined
    at fetcher (/Users/julien/Documents/JulienGit/TeslaInventory/fetchTeslaInventory.js:3:35)
    at pRetry.onFailedAttempt (/Users/julien/Documents/JulienGit/TeslaInventory/node_modules/tesla-inventory/src/index.js:48:9)
    at RetryOperation._fn (/Users/julien/Documents/JulienGit/TeslaInventory/node_modules/p-retry/index.js:50:18)
    at Timeout._onTimeout (/Users/julien/Documents/JulienGit/TeslaInventory/node_modules/retry/lib/retry_operation.js:85:10)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:48334) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:48334) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Kikobeats** [comment]
weird, see the example on tests:
https://github.com/teslahunt/tesla-inventory/blob/c2067d40304094e183d85c2e1a4907ff477250ee/test/util.js#L9
